import { createFileRoute } from "@tanstack/react-router";
import { PageHeader, Card, Pill } from "@/components/app/Primitives";
import { Brain, ChevronRight } from "lucide-react";
import { motion } from "framer-motion";
import { useQuery } from "@tanstack/react-query";
import { getMarketBrief } from "@/functions/market-brief.functions";
import { toast } from "sonner";

export const Route = createFileRoute("/app/market-brief")({
  component: MarketBrief,
});

function MarketBrief() {
  const { data: briefData, isLoading } = useQuery({
    queryKey: ["market-brief"],
    queryFn: () => getMarketBrief(),
  });

  const brief = briefData?.data;
  const sections = brief?.sections ?? [];
  const actionables = brief?.actionables ?? [];
  const pastBriefs = brief?.pastBriefs ?? [];

  const handleListen = () => {
    toast.info("Audio synthesis is a Pro feature. Processing preview...", {
      duration: 3000
    });
  };

  return (
    <div>
      <PageHeader
        title="Market Brief"
        subtitle={brief?.date ?? "Generated by TradeOS AI"}
        actions={
          <button 
            onClick={handleListen}
            className="rounded-lg bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground hover:opacity-90 transition-all cursor-pointer"
          >
            Listen (4 min)
          </button>
        }
      />
      <div className="grid grid-cols-12 gap-4 p-6">
        <Card className="col-span-12 xl:col-span-8">
          <div className="flex items-center gap-2 text-xs text-primary font-medium">
            <Brain className="h-4 w-4" /> AI Synthesis
          </div>
          {isLoading ? (
            <div className="py-12 text-center text-sm text-muted-foreground flex flex-col items-center gap-2">
              <div className="h-6 w-6 animate-spin rounded-full border-2 border-primary/30 border-t-primary" />
              <span>Generating daily market brief...</span>
            </div>
          ) : (
            <>
              <h2 className="mt-2 text-2xl font-semibold leading-snug">
                {brief?.synthesisTitle}
              </h2>
              <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
                {brief?.synthesisBody}
              </p>
              <div className="mt-6 space-y-4">
                {sections.map((s, i) => (
                  <motion.div
                    key={s.title}
                    initial={{ opacity: 0, x: -8 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.06 }}
                    className="border-l-2 border-primary/40 pl-4"
                  >
                    <div className="text-sm font-semibold">{s.title}</div>
                    <p className="mt-1 text-sm text-muted-foreground leading-relaxed">{s.body}</p>
                  </motion.div>
                ))}
              </div>
            </>
          )}
        </Card>

        <div className="col-span-12 space-y-4 xl:col-span-4">
          <Card title="Today's Actionables">
            {isLoading ? (
              <div className="py-6 text-center text-sm text-muted-foreground flex justify-center items-center">
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-primary/30 border-t-primary" />
              </div>
            ) : (
              <ul className="space-y-3 text-sm">
                {actionables.map((a) => (
                  <li key={a.sym} className="flex items-start justify-between gap-3">
                    <div>
                      <div className="text-sm font-semibold">{a.sym}</div>
                      <div className="text-xs text-muted-foreground">{a.note}</div>
                    </div>
                    <Pill tone={a.tag === "Long" ? "success" : a.tag === "Avoid" ? "danger" : "warn"}>
                      {a.tag}
                    </Pill>
                  </li>
                ))}
              </ul>
            )}
          </Card>

          <Card title="Past Briefs">
            <ul className="space-y-1 text-sm">
              {pastBriefs.map((d) => (
                <li
                  key={d}
                  className="flex items-center justify-between rounded-lg px-2 py-1.5 hover:bg-secondary transition-all cursor-pointer group"
                >
                  <span>{d}</span>
                  <ChevronRight className="h-4 w-4 text-muted-foreground group-hover:translate-x-0.5 transition-transform" />
                </li>
              ))}
            </ul>
          </Card>
        </div>
      </div>
    </div>
  );
}
